name: Engine CI (MSBuild + GoogleTest)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Restore NuGet packages
      run: nuget restore SystemsPlayground.slnx

    - name: Build solution (Debug)
      run: msbuild SystemsPlayground.slnx /p:Configuration=Debug /m

    - name: Run Google Tests and produce XML report
      run: |
        Tests\SystemsPlaygroundTests\build\x64\Debug\SystemsPlaygroundTests.exe --gtest_output=xml:test_results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: gtest-results
        path: test_results.xml
        
    - name: Test Report
      uses: dorny/test-reporter@v2
      
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
          name: JEST Tests            # Name of the check run which will be created
          path: test_results.xml    # Path to test results
          reporter: jest-junit        # Format of test results
